### ISSUE TITLE
Request for Comments: provided_magic

### ISSUE THREAD

**Issue by vanHoesel** [tobyink/p5-perlx-maybe#3]
Hey Toby, this is an interesting gem you wrote, makes our code look so much cleaner!

However, we have situations where we have one single condition and if provided, then we'll set multiple key/values, like:

```perl
my $hash = {
    foo => 'theo',
    ( $bool )
    ? (
        bar => 'love',
        baz => 'pink',
    )
    : ( ),
    qux => 'more',
}
```

wouldn't it be nice that it would fit into your nifty `provided`, where the 2nd argument wild be dereferenced into list context when provided that the 1st argument evaluates to 'true' ?

```perl
my $hash = {
        foo => 'theo',
    provided_deref $bool, {
        bar => 'love',
        baz => 'pink',
    },
        qux => 'more',
}
```

**Comment by vanHoesel** [comment]
I also added some more DWIM with `provided_maybe`

See Mergerequest #4

**Comment by tobyink** [comment]
1.200
